ekf_odom_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false
    publish_tf: true      # 실시간 주행용 (bag 오프라인 분석이면 false도 가능)

    # 프레임
    map_frame: odom
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    ########################
    # wheel odom (vesc_driver)
    ########################
    odom0: /odom
    odom0_config: [
      true,  true,  false,   # x, y, z
      false, false, false,   # roll, pitch, yaw
      true,  false, false,   # v_x, v_y, v_z
      false, false, true,    # ω_x, ω_y, ω_z (원하면 true/false 조절)
      false, false, false    # a_x, a_y, a_z
    ]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10

    ########################
    # IMU
    ########################
    imu0: /imu     
    imu0_config: [
      false, false, false,  # x, y, z
      true,  true,  true,   # roll, pitch, yaw
      false, false, false,  # v_x, v_y, v_z
      true,  true,  true,   # ω_x, ω_y, ω_z
      true,  true,  true    # a_x, a_y, a_z
    ]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 20
    imu0_remove_gravitational_acceleration: true

    use_control: false

